[package]
name = "device-types"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
im = { version = "12.0.0", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "0.5"
serde_json = "1.0"
