[package]
name = "futures-failure"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
license = "MIT"

[dependencies]
futures = "0.1"
failure = "0.1.3"

[dev-dependencies]
pretty_assertions = "0.5"

