[package]
name = "device-scanner-daemon"
version = "2.0.0"
description = "device-scanner-daemon builds an in-memory representation of devices using udev, zed and findmnt"
authors = ["IML Team <iml@whamcloud.com>"]
autobins = false

[[bin]]
path = "src/bin/device_scanner_daemon.rs"
name = "device-scanner-daemon"
doc = false


[dependencies]
tokio = "0.1"
futures = "0.1"
failure = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
im = { version = "12.0.0", features = ["serde"] }
device-types = { path = "../device-types", version = "0.1.0" }
futures-failure = { path = "../futures-failure", version = "0.1.0" }

[dev-dependencies]
pretty_assertions = "0.5"
tokio-mockstream = "1.1"
